apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: rds!db-f60c8611-800a-42d3-94ba-61cfc2d943bf
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: rds!db-f60c8611-800a-42d3-94ba-61cfc2d943bf
        property: password
